#使用定数放置行人速度,长,宽
PERS_SPEED = 4
PERS_HEIGHT = 10
PERS_WIDTH = 20

#使用定数放置车辆速度,车辆长,宽
CAR_HEIGHT = 80
CAR_WIDTH = 40

CAR_ACCELERATE = 1 # 加速度
CAR_INITIAL = 0 # 初速度
CAR_SPEED = 15 # 最高速

RED_TIME = 15 # 红灯时长
YELLOW_TIME = 4 # 黄灯时长

C_WAITVALUE = 4
P_WAITVALUE = 1

WAITTIME_LIMIT = 30 # 最大负荷值为30s

# 出现频度
HIGH_FREQUENT = 15 
MIDDLE_FREQUENT = 30
LOW_FREQUENT = 50